//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport_Company_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportCompanyDBEntities : DbContext
    {

        private static TransportCompanyDBEntities _instace;

        public TransportCompanyDBEntities()
            : base("name=TransportCompanyDBEntities")
        {
        }

        public static TransportCompanyDBEntities GetContext()
        {
            if (_instace == null)
            {
                _instace = new TransportCompanyDBEntities();
            }
            return _instace;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Водители> Водители { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<История_заказов> История_заказов { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Маршруты> Маршруты { get; set; }
        public virtual DbSet<Транспорт> Транспорт { get; set; }
    }
}
