//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport_Company_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.История_заказов = new HashSet<История_заказов>();
        }
    
        public int ID_заказа { get; set; }
        public Nullable<int> ID_водителя { get; set; }
        public Nullable<int> ID_транспорта { get; set; }
        public Nullable<int> ID_маршрута { get; set; }
        public Nullable<System.DateTime> Дата_время_заказа { get; set; }
        public string Статус_заказа { get; set; }
    
        public virtual Водители Водители { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_заказов> История_заказов { get; set; }
        public virtual Маршруты Маршруты { get; set; }
        public virtual Транспорт Транспорт { get; set; }
    }
}
