//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport_Company_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_заказов
    {
        public int ID_записи { get; set; }
        public Nullable<int> ID_заказа { get; set; }
        public Nullable<int> ID_клиента { get; set; }
        public Nullable<System.DateTime> ДатаВыполненияВремя { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
