//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport_Company_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршруты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Маршруты()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int ID_маршрута { get; set; }
        public string Начальная_точка { get; set; }
        public string Конечная_точка { get; set; }
        public Nullable<double> Дистанция { get; set; }
        public Nullable<System.TimeSpan> Время_в_пути { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
