//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport_Company_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Транспорт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Транспорт()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int ID_транспорта { get; set; }
        public string Бренд { get; set; }
        public string Модель { get; set; }
        public Nullable<int> Год { get; set; }
        public string Номерной_знак { get; set; }
        public Nullable<int> Емкость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
